baseURL: https://dev.com.cn/
languageCode: zh-CN
title: DEV
theme: "PaperMod"
defaultTheme: "dark"

params:
  env: production
  assets:
    favicon: /favicon.png
    favicon16x16: /favicon.png
    favicon32x32: /favicon.png
    apple_touch_icon: /apple-touch-icon.png
    safari_pinned_tab: /apple-touch-icon.png

  label:
    text: "DEV"
    icon: /logo.png
    iconHeight: 30

  editPost:
    URL: "https://github.com/thebetterdev/dev/edit/main/content"
    Text: "IMPROVE THIS PAGE"
    appendFilePath: true

menu:
  main:
    - identifier: github
      name: GitHub
      url: https://github.com/thebetterdev/dev
      weight: 10